from typing import Any

actor: Any
exceptions: Any
util: Any

def cluster_resources() -> dict[str, float]: ...
def get(ref: Any, *args: Any, **kwargs: Any) -> Any: ...
def get_actor(*args: Any, **kwargs: Any) -> Any: ...
def init(*args: Any, **kwargs: Any) -> Any: ...
def is_initialized() -> bool: ...
def kill(*args: Any, **kwargs: Any) -> None: ...
def method(*args: Any, **kwargs: Any) -> Any: ...
def nodes() -> list[dict[str, Any]]: ...
def remote(*args: Any, **kwargs: Any) -> Any: ...
