#!/usr/bin/env python3
"""Generate a mint_dev_run.env file for the current Ray cluster.

Reads worker IPs from the Ray dashboard and writes a placement config
file that maps models to specific worker nodes.

Usage:
    HEAD_IP=$(cat /vePFS-Mindverse/share/mint/dev/ray/head-address/ray_head_ip.txt)
    python scripts/tools/gen_dev_placement.py --head-ip $HEAD_IP \
        --model Qwen/Qwen3-0.6B --gpu-count 1 \
        --output /tmp/mint_dev_run.env
"""
from __future__ import annotations

import argparse
import json
import urllib.request


def get_worker_ips(head_ip: str) -> list[tuple[str, int]]:
    """Get (ip, gpu_count) for all alive GPU workers from Ray dashboard."""
    url = f"http://{head_ip}:8265/api/cluster_status"
    with urllib.request.urlopen(url, timeout=10) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    lm = data.get("data", {}).get("clusterStatus", {}).get("loadMetricsReport", {})
    node_types = lm.get("nodeTypes", [])
    workers = []
    for nt, _count in node_types:
        gpu = int(nt.get("GPU", 0) or 0)
        if gpu <= 0:
            continue
        for k in nt:
            if k.startswith("node:") and k != "node:__internal_head__":
                ip = k[5:]
                workers.append((ip, gpu))
                break
    return workers


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--head-ip", required=True, help="Ray head node IP")
    parser.add_argument("--model", action="append", required=True, help="Model name (repeatable)")
    parser.add_argument("--gpu-count", type=int, default=1, help="GPUs per model (default: 1)")
    parser.add_argument("--max-model-len", type=int, default=32768, help="Max model length (default: 32768)")
    parser.add_argument("--output", default="/tmp/mint_dev_run.env", help="Output file path")
    args = parser.parse_args()

    workers = get_worker_ips(args.head_ip)
    if not workers:
        print(f"error: no GPU workers found on head {args.head_ip}")
        return 1

    print(f"Found {len(workers)} GPU workers:")
    for ip, gpu in workers:
        print(f"  {ip}: {gpu} GPUs")

    # Assign models to workers (round-robin)
    placement = {}
    for i, model in enumerate(args.model):
        worker_ip, _ = workers[i % len(workers)]
        placement[model] = {"replica": 0, "node_ip": worker_ip, "gpu_count": args.gpu_count}

    placement_json = json.dumps(placement)
    overrides = {m: {"max_model_len": args.max_model_len} for m in args.model}
    overrides_json = json.dumps(overrides)

    with open(args.output, "w") as f:
        f.write("# Auto-generated by scripts/tools/gen_dev_placement.py\n")
        f.write(f"# Cluster head: {args.head_ip}\n")
        f.write(f'export MINT_DENSE_MODEL_PLACEMENT_JSON={placement_json!r}\n')
        f.write(f'export MINT_VLLM_MODEL_PLACEMENT_JSON={placement_json!r}\n')
        f.write(f'export MINT_MODEL_CONFIG_OVERRIDES_JSON={overrides_json!r}\n')
        f.write("export MINT_CHECKPOINT_DIR=/vePFS-Mindverse/share/mint/dev/data/checkpoints\n")

    print(f"\nWrote {args.output}")
    print(f"  Models: {', '.join(args.model)}")
    print(f"  Placement: {placement}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
