#!/bin/bash
set -euo pipefail

# Start one isolated mint-dev issue server from the shared dev config template.
# This script is meant to run on the mint-dev host after the issue worktree has
# been synced to PFS. Model work is admitted through ModelWorkScheduler and
# executed by Ray-backed model runtime actors.

: "${ISSUE_SERVER_ROOT:=/root/tinker_project/tinker-server-issue-416}"

_INPUT_RAY_ADDRESS="${RAY_ADDRESS:-}"
_INPUT_MINT_RAY_CLIENT_ADDRESS="${MINT_RAY_CLIENT_ADDRESS:-}"
_INPUT_PFS_TINKER_PATH="${PFS_TINKER_PATH:-}"
_INPUT_MINT_RAY_PY_MODULES_CSV="${MINT_RAY_PY_MODULES_CSV:-}"
_INPUT_MINT_VLLM_CHILD_PYTHON_EXECUTABLE="${MINT_VLLM_CHILD_PYTHON_EXECUTABLE:-}"

cd "${ISSUE_SERVER_ROOT}"
dev_config_env="${MINT_DEV_CONFIG_ENV:-/share/mint/dev/config/common.env}"
if [[ ! -r "${dev_config_env}" ]]; then
  echo "missing dev config: ${dev_config_env}" >&2
  exit 1
fi
. "${dev_config_env}"

export RAY_ADDRESS="${_INPUT_RAY_ADDRESS:-${RAY_ADDRESS:-}}"
export MINT_RAY_CLIENT_ADDRESS="${_INPUT_MINT_RAY_CLIENT_ADDRESS:-${MINT_RAY_CLIENT_ADDRESS:-${RAY_ADDRESS}}}"
export PFS_TINKER_PATH="${_INPUT_PFS_TINKER_PATH:-${PFS_TINKER_PATH:-}}"
export MINT_RAY_PY_MODULES_CSV="${_INPUT_MINT_RAY_PY_MODULES_CSV:-}"
export MINT_VLLM_CHILD_PYTHON_EXECUTABLE="${_INPUT_MINT_VLLM_CHILD_PYTHON_EXECUTABLE:-}"

: "${RAY_ADDRESS:?set RAY_ADDRESS=ray://<head>:10001}"
: "${MINT_RAY_CLIENT_ADDRESS:?set MINT_RAY_CLIENT_ADDRESS=ray://<head>:10001}"
: "${PFS_TINKER_PATH:?set PFS_TINKER_PATH=/vePFS-Mindverse/share/code/<user>/tinker-server-issue-<n>}"
: "${ISSUE_NAMESPACE:?set ISSUE_NAMESPACE=tinker_<user>_issue_<n>}"
: "${ISSUE_STARTUP_LEASE:?set ISSUE_STARTUP_LEASE=tinker_startup_lease_<n>}"
: "${ISSUE_PORT:?set ISSUE_PORT=10416}"
: "${ISSUE_LOG_FILE:?set ISSUE_LOG_FILE=/tmp/tinker_server_issue.log}"
: "${ISSUE_USAGE_LOG_DIR:?set ISSUE_USAGE_LOG_DIR=/tmp/tinker_usage_issue}"
: "${ISSUE_SUPPORTED_MODELS:?set ISSUE_SUPPORTED_MODELS=Qwen/Qwen3-30B-A3B-Instruct-2507}"
: "${ISSUE_MODEL_PLACEMENT_JSON:?set ISSUE_MODEL_PLACEMENT_JSON={}}"
: "${ISSUE_MEGATRON_MODEL_PLACEMENT_JSON:=${ISSUE_MODEL_PLACEMENT_JSON}}"
: "${ISSUE_DENSE_MODEL_PLACEMENT_JSON:={\}}"
: "${ISSUE_VLLM_MODEL_PLACEMENT_JSON:={\}}"

export RAY_ADDRESS
export MINT_RAY_CLIENT_ADDRESS
export PFS_TINKER_PATH
export MINT_RAY_PY_MODULES_CSV="${MINT_RAY_PY_MODULES_CSV:-${PFS_TINKER_PATH}/tinker_server}"
export MINT_VLLM_CHILD_PYTHON_EXECUTABLE="${MINT_VLLM_CHILD_PYTHON_EXECUTABLE:-${PFS_TINKER_PATH}/scripts/vllm_worker_python.py}"

export TINKER_RAY_NAMESPACE="${ISSUE_NAMESPACE}"
export MINT_RAY_NAMESPACE="${ISSUE_NAMESPACE}"
export MINT_STARTUP_LEASE_ACTOR_NAME="${ISSUE_STARTUP_LEASE}"

ISSUE_NAME_SUFFIX="$(printf '%s' "${ISSUE_NAMESPACE}" | tr -c '[:alnum:]' '_')"
export MINT_MODEL_WORK_SCHEDULER_ACTOR_NAME="mint_model_work_scheduler_${ISSUE_NAME_SUFFIX}"
export MINT_TASK_STATE_STORE_ACTOR_NAME="mint_task_state_store_${ISSUE_NAME_SUFFIX}"
export MINT_GATEWAY_SESSION_STORE_ACTOR_NAME="tinker_gateway_session_store_${ISSUE_NAME_SUFFIX}"
export MINT_SAMPLING_SESSION_STORE_ACTOR_NAME="tinker_sampling_session_store_${ISSUE_NAME_SUFFIX}"
export MINT_TRAINING_SESSION_STORE_ACTOR_NAME="tinker_training_session_store_${ISSUE_NAME_SUFFIX}"
export MINT_SESSION_HEARTBEAT_ACTOR_NAME="tinker_session_heartbeat_store_${ISSUE_NAME_SUFFIX}"
export MINT_SESSION_INDEX_ACTOR_NAME="tinker_session_index_store_${ISSUE_NAME_SUFFIX}"
export MINT_MAINTENANCE_CRON_ACTOR_NAME="mint_maintenance_cron_${ISSUE_NAME_SUFFIX}"
export MINT_TRAINING_CLEANUP_EXECUTOR_ACTOR_NAME="tinker_training_cleanup_executor_${ISSUE_NAME_SUFFIX}"
export MINT_SAMPLING_CLEANUP_EXECUTOR_ACTOR_NAME="tinker_sampling_cleanup_executor_${ISSUE_NAME_SUFFIX}"
export MINT_FUTURE_REPLAY_SWEEPER_ACTOR_NAME="mint_future_replay_sweeper_${ISSUE_NAME_SUFFIX}"
export MINT_MODEL_WORK_SCHEDULER_DEBUG_LOG_PATH="/tmp/mint_model_work_scheduler.${ISSUE_NAME_SUFFIX}.debug.jsonl"

export TINKER_PORT="${ISSUE_PORT}"
export TINKER_API_KEY="${TINKER_API_KEY:-dummy}"
export MINT_LOG_FILE="${ISSUE_LOG_FILE}"
export TINKER_USAGE_LOG_DIR="${ISSUE_USAGE_LOG_DIR}"

export MINT_SUPPORTED_MODELS="${ISSUE_SUPPORTED_MODELS}"
export MINT_PERSISTENT_MODELS=""
export MINT_PERSISTENT_PREWARM_TRAINING=0
export MINT_PERSISTENT_PREWARM_INFERENCE=0
export MINT_UVICORN_WORKERS=1
export MINT_OAI_PRELOAD_TOKENIZERS=0
export MINT_DISABLE_MINT_ROUTE=1

export MINT_CONTROL_PLANE_PINNED_NODE_IP="${MINT_CONTROL_PLANE_PINNED_NODE_IP:-192.168.39.87}"
export MINT_STARTUP_LEASE_PINNED_NODE_IP="${MINT_STARTUP_LEASE_PINNED_NODE_IP:-192.168.39.87}"
export MINT_MODEL_WORK_SCHEDULER_PINNED_NODE_IP="${MINT_MODEL_WORK_SCHEDULER_PINNED_NODE_IP:-192.168.39.87}"
export MINT_DETACHED_ACTOR_NODE_IP="${MINT_DETACHED_ACTOR_NODE_IP:-192.168.39.87}"

export MINT_DENSE_MODEL_PLACEMENT_JSON="${ISSUE_DENSE_MODEL_PLACEMENT_JSON}"
export MINT_MODEL_PLACEMENT_JSON="${ISSUE_MODEL_PLACEMENT_JSON}"
export MINT_VLLM_MODEL_PLACEMENT_JSON="${ISSUE_VLLM_MODEL_PLACEMENT_JSON}"
export MINT_MEGATRON_MODEL_PLACEMENT_JSON="${ISSUE_MEGATRON_MODEL_PLACEMENT_JSON}"

if [[ "${ISSUE_STARTUP_PRINT_ENV:-0}" == "1" ]]; then
  env | grep -E '^(RAY_ADDRESS|MINT_RAY_CLIENT_ADDRESS|PFS_TINKER_PATH|MINT_RAY_PY_MODULES_CSV|MINT_VLLM_CHILD_PYTHON_EXECUTABLE|TINKER_RAY_NAMESPACE|MINT_RAY_NAMESPACE|MINT_STARTUP_LEASE_ACTOR_NAME|MINT_MODEL_WORK_SCHEDULER_ACTOR_NAME|MINT_TASK_STATE_STORE_ACTOR_NAME|MINT_GATEWAY_SESSION_STORE_ACTOR_NAME|MINT_SAMPLING_SESSION_STORE_ACTOR_NAME|MINT_TRAINING_SESSION_STORE_ACTOR_NAME|MINT_SESSION_HEARTBEAT_ACTOR_NAME|MINT_SESSION_INDEX_ACTOR_NAME|MINT_MAINTENANCE_CRON_ACTOR_NAME|MINT_TRAINING_CLEANUP_EXECUTOR_ACTOR_NAME|MINT_SAMPLING_CLEANUP_EXECUTOR_ACTOR_NAME|MINT_FUTURE_REPLAY_SWEEPER_ACTOR_NAME|MINT_DISABLE_MINT_ROUTE|TINKER_API_KEY|TINKER_PORT|MINT_LOG_FILE|TINKER_USAGE_LOG_DIR|MINT_MODEL_PLACEMENT_JSON|MINT_DENSE_MODEL_PLACEMENT_JSON|MINT_VLLM_MODEL_PLACEMENT_JSON|MINT_MEGATRON_MODEL_PLACEMENT_JSON)=' | sort
  exit 0
fi

exec "${PFS_RUNTIME_ENV_ROOT}/host-venv/bin/python" scripts/run_server.py
