#!/bin/bash
set -euo pipefail

# Start one isolated mint-dev issue server from the checked-in dev template.
# This script is meant to run on the mint-dev host after the issue worktree has
# been synced to PFS. It uses the existing local queue-runtime mode so training
# route globals are bound in the API process while the actual model work still
# uses Ray-backed engines.

: "${ISSUE_SERVER_ROOT:=/root/tinker_project/tinker-server-issue-416}"

_INPUT_RAY_ADDRESS="${RAY_ADDRESS:-}"
_INPUT_MINT_RAY_CLIENT_ADDRESS="${MINT_RAY_CLIENT_ADDRESS:-}"
_INPUT_PFS_TINKER_PATH="${PFS_TINKER_PATH:-}"
_INPUT_MINT_RAY_PY_MODULES_CSV="${MINT_RAY_PY_MODULES_CSV:-}"
_INPUT_MINT_VLLM_CHILD_PYTHON_EXECUTABLE="${MINT_VLLM_CHILD_PYTHON_EXECUTABLE:-}"

cd "${ISSUE_SERVER_ROOT}"
. ./configs/dev_volcano.env.sh

export RAY_ADDRESS="${_INPUT_RAY_ADDRESS:-${RAY_ADDRESS:-}}"
export MINT_RAY_CLIENT_ADDRESS="${_INPUT_MINT_RAY_CLIENT_ADDRESS:-${MINT_RAY_CLIENT_ADDRESS:-${RAY_ADDRESS}}}"
export PFS_TINKER_PATH="${_INPUT_PFS_TINKER_PATH:-${PFS_TINKER_PATH:-}}"
export MINT_RAY_PY_MODULES_CSV="${_INPUT_MINT_RAY_PY_MODULES_CSV:-}"
export MINT_VLLM_CHILD_PYTHON_EXECUTABLE="${_INPUT_MINT_VLLM_CHILD_PYTHON_EXECUTABLE:-}"

: "${RAY_ADDRESS:?set RAY_ADDRESS=ray://<head>:10001}"
: "${MINT_RAY_CLIENT_ADDRESS:?set MINT_RAY_CLIENT_ADDRESS=ray://<head>:10001}"
: "${PFS_TINKER_PATH:?set PFS_TINKER_PATH=/vePFS-Mindverse/share/code/<user>/tinker-server-issue-<n>}"
: "${ISSUE_NAMESPACE:?set ISSUE_NAMESPACE=tinker_<user>_issue_<n>}"
: "${ISSUE_STARTUP_LEASE:?set ISSUE_STARTUP_LEASE=tinker_startup_lease_<n>}"
: "${ISSUE_PORT:?set ISSUE_PORT=10416}"
: "${ISSUE_LOG_FILE:?set ISSUE_LOG_FILE=/tmp/tinker_server_issue.log}"
: "${ISSUE_USAGE_LOG_DIR:?set ISSUE_USAGE_LOG_DIR=/tmp/tinker_usage_issue}"
: "${ISSUE_SUPPORTED_MODELS:?set ISSUE_SUPPORTED_MODELS=Qwen/Qwen3-30B-A3B-Instruct-2507}"
: "${ISSUE_MODEL_NODE_IPS_JSON:?set ISSUE_MODEL_NODE_IPS_JSON={}}"
: "${ISSUE_MEGATRON_MODEL_NODE_IPS_JSON:?set ISSUE_MEGATRON_MODEL_NODE_IPS_JSON=${ISSUE_MODEL_NODE_IPS_JSON}}"
: "${ISSUE_DENSE_MODEL_NODE_IPS_JSON:=\{\}}"
: "${ISSUE_VLLM_MODEL_NODE_IPS_JSON:=\{\}}"
: "${ISSUE_VLLM_PINNED_NODE_IP_JSON:=\{\}}"

export RAY_ADDRESS
export MINT_RAY_CLIENT_ADDRESS
export PFS_TINKER_PATH
export MINT_RAY_PY_MODULES_CSV="${MINT_RAY_PY_MODULES_CSV:-${PFS_TINKER_PATH}/tinker_server}"
export MINT_VLLM_CHILD_PYTHON_EXECUTABLE="${MINT_VLLM_CHILD_PYTHON_EXECUTABLE:-${PFS_TINKER_PATH}/scripts/vllm_worker_python.py}"

export TINKER_RAY_NAMESPACE="${ISSUE_NAMESPACE}"
export MINT_RAY_NAMESPACE="${ISSUE_NAMESPACE}"
export MINT_STARTUP_LEASE_ACTOR_NAME="${ISSUE_STARTUP_LEASE}"

ISSUE_NAME_SUFFIX="$(printf '%s' "${ISSUE_NAMESPACE}" | tr -c '[:alnum:]' '_')"
export MINT_API_WORK_QUEUE_ACTOR_NAME="tinker_api_work_queue_${ISSUE_NAME_SUFFIX}"
export MINT_CAPACITY_MANAGER_ACTOR_NAME="tinker_capacity_manager_${ISSUE_NAME_SUFFIX}"
export MINT_QUEUE_EXECUTION_RUNTIME_ACTOR_NAME="tinker_queue_execution_runtime_${ISSUE_NAME_SUFFIX}"
export MINT_QUEUE_SUPERVISOR_ACTOR_NAME="tinker_queue_supervisor_${ISSUE_NAME_SUFFIX}"
export MINT_FUTURE_STORE_ACTOR_NAME="tinker_future_store_${ISSUE_NAME_SUFFIX}"
export MINT_GATEWAY_SESSION_STORE_ACTOR_NAME="tinker_gateway_session_store_${ISSUE_NAME_SUFFIX}"
export MINT_SAMPLING_SESSION_STORE_ACTOR_NAME="tinker_sampling_session_store_${ISSUE_NAME_SUFFIX}"
export MINT_TRAINING_SESSION_STORE_ACTOR_NAME="tinker_training_session_store_${ISSUE_NAME_SUFFIX}"
export MINT_SESSION_HEARTBEAT_ACTOR_NAME="tinker_session_heartbeat_store_${ISSUE_NAME_SUFFIX}"
export MINT_SESSION_INDEX_ACTOR_NAME="tinker_session_index_store_${ISSUE_NAME_SUFFIX}"
export MINT_RESOURCE_POOL_ACTOR_NAME="tinker_resource_pool_${ISSUE_NAME_SUFFIX}"
export MINT_OWNER_RUNTIME_SUPERVISOR_ACTOR_NAME="tinker_owner_runtime_supervisor_${ISSUE_NAME_SUFFIX}"
export MINT_TRAINING_CLEANUP_EXECUTOR_ACTOR_NAME="tinker_training_cleanup_executor_${ISSUE_NAME_SUFFIX}"
export MINT_SAMPLING_CLEANUP_EXECUTOR_ACTOR_NAME="tinker_sampling_cleanup_executor_${ISSUE_NAME_SUFFIX}"
export MINT_FUTURE_REPLAY_SWEEPER_ACTOR_NAME="mint_future_replay_sweeper_${ISSUE_NAME_SUFFIX}"
export MINT_API_WORK_QUEUE_DEBUG_LOG_PATH="/tmp/tinker_api_work_queue.${ISSUE_NAME_SUFFIX}.debug.jsonl"
export MINT_QUEUE_EXECUTION_RUNTIME_DEBUG_LOG_PATH="/tmp/tinker_queue_execution_runtime.${ISSUE_NAME_SUFFIX}.debug.jsonl"

export TINKER_PORT="${ISSUE_PORT}"
export TINKER_API_KEY="${TINKER_API_KEY:-dummy}"
export MINT_LOG_FILE="${ISSUE_LOG_FILE}"
export TINKER_USAGE_LOG_DIR="${ISSUE_USAGE_LOG_DIR}"

export MINT_SUPPORTED_MODELS="${ISSUE_SUPPORTED_MODELS}"
export MINT_PERSISTENT_MODELS=""
export MINT_PERSISTENT_PREWARM_TRAINING=0
export MINT_PERSISTENT_PREWARM_INFERENCE=0
export MINT_UVICORN_WORKERS=1
export MINT_OAI_PRELOAD_TOKENIZERS=0
export MINT_DISABLE_MINT_ROUTE=1

# Bind training globals in the API process for isolated issue servers while
# keeping Ray-backed training/inference engines underneath.
export MINT_QUEUE_EXECUTION_RUNTIME_LOCAL_ONLY=1
# Local-only issue servers should bind and accept requests once the local
# execution runtime is initialized, even if the detached queue path has not yet
# flipped its execution-ready event.
export MINT_API_WORK_QUEUE_SKIP_READY_WAIT=1

export MINT_CONTROL_PLANE_PINNED_NODE_IP="${MINT_CONTROL_PLANE_PINNED_NODE_IP:-192.168.39.87}"
export MINT_API_WORK_QUEUE_PINNED_NODE_IP="${MINT_API_WORK_QUEUE_PINNED_NODE_IP:-192.168.39.87}"
export MINT_STARTUP_LEASE_PINNED_NODE_IP="${MINT_STARTUP_LEASE_PINNED_NODE_IP:-192.168.39.87}"
export MINT_DETACHED_ACTOR_NODE_IP="${MINT_DETACHED_ACTOR_NODE_IP:-192.168.39.87}"

export MINT_DENSE_MODEL_NODE_IPS_JSON="${ISSUE_DENSE_MODEL_NODE_IPS_JSON}"
export MINT_MODEL_NODE_IPS_JSON="${ISSUE_MODEL_NODE_IPS_JSON}"
export MINT_VLLM_MODEL_NODE_IPS_JSON="${ISSUE_VLLM_MODEL_NODE_IPS_JSON}"
export MINT_MEGATRON_MODEL_NODE_IPS_JSON="${ISSUE_MEGATRON_MODEL_NODE_IPS_JSON}"
export MINT_VLLM_PINNED_NODE_IP_JSON="${ISSUE_VLLM_PINNED_NODE_IP_JSON}"

if [[ "${ISSUE_STARTUP_PRINT_ENV:-0}" == "1" ]]; then
  env | grep -E '^(RAY_ADDRESS|MINT_RAY_CLIENT_ADDRESS|PFS_TINKER_PATH|MINT_RAY_PY_MODULES_CSV|MINT_VLLM_CHILD_PYTHON_EXECUTABLE|TINKER_RAY_NAMESPACE|MINT_RAY_NAMESPACE|MINT_STARTUP_LEASE_ACTOR_NAME|MINT_API_WORK_QUEUE_ACTOR_NAME|MINT_CAPACITY_MANAGER_ACTOR_NAME|MINT_QUEUE_EXECUTION_RUNTIME_ACTOR_NAME|MINT_QUEUE_SUPERVISOR_ACTOR_NAME|MINT_FUTURE_STORE_ACTOR_NAME|MINT_GATEWAY_SESSION_STORE_ACTOR_NAME|MINT_SAMPLING_SESSION_STORE_ACTOR_NAME|MINT_TRAINING_SESSION_STORE_ACTOR_NAME|MINT_SESSION_HEARTBEAT_ACTOR_NAME|MINT_SESSION_INDEX_ACTOR_NAME|MINT_RESOURCE_POOL_ACTOR_NAME|MINT_OWNER_RUNTIME_SUPERVISOR_ACTOR_NAME|MINT_TRAINING_CLEANUP_EXECUTOR_ACTOR_NAME|MINT_SAMPLING_CLEANUP_EXECUTOR_ACTOR_NAME|MINT_FUTURE_REPLAY_SWEEPER_ACTOR_NAME|MINT_QUEUE_EXECUTION_RUNTIME_LOCAL_ONLY|MINT_DISABLE_MINT_ROUTE|TINKER_API_KEY|TINKER_PORT|MINT_LOG_FILE|TINKER_USAGE_LOG_DIR)=' | sort
  exit 0
fi

exec /vePFS-Mindverse/share/code/mint-runtime-py31213/host-venv/bin/python scripts/run_server.py
