from typing import Any

def get_placement_group(*args: Any, **kwargs: Any) -> Any: ...
def list_named_actors(*args: Any, **kwargs: Any) -> list[str]: ...
def placement_group(*args: Any, **kwargs: Any) -> Any: ...
def placement_group_table(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def remove_placement_group(*args: Any, **kwargs: Any) -> None: ...
